import { getAttendanceSummary, getCourse, listCoursesForStudent, listLeavesForStudent } from './db';
import { MOCK_COURSES } from './mockTeacherData';

export const MOCK_STUDENT_COURSES = [
  {
    id: 'mock-sc1',
    code: '24527664',
    name: 'การวิเคราะห์และออกแบบระบบสารสนเทศ',
    term: '1/2569',
    group: '2',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.อัครา',
    day: 'MO',
    time: '09:00-11:50',
    room: 'QS2-701',
    teacher: { id: 't1', name: 'ผศ.ดร.อัครา' },
  },
  {
    id: 'mock-sc2',
    code: '24537364',
    name: 'ระบบห้องสมุดอัตโนมัติ',
    term: '1/2569',
    group: '2',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.ปรียานุช',
    day: 'MO',
    time: '13:00-16:50',
    room: 'QS2-407',
    teacher: { id: 't4', name: 'ผศ.ดร.ปรียานุช' },
  },
  {
    id: 'mock-sc3',
    code: '24527364',
    name: 'การสื่อสารข้อมูลและเครือข่ายคอมพิวเตอร์',
    term: '1/2569',
    group: '2',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.ฉัชพน',
    day: 'TU',
    time: '17:00-19:50',
    room: 'QS2-415',
    teacher: { id: 't8', name: 'ผศ.ดร.ฉัชพน' },
  },
  {
    id: 'mock-sc4',
    code: '24535164',
    name: 'การจัดการทรัพยากรสารสนเทศ',
    term: '1/2569',
    group: '2',
    totalSessions: 15,
    teacherName: 'อ.สมฤทัย',
    day: 'TH',
    time: '16:00-18:50',
    room: 'QS2-415',
    teacher: { id: 't3', name: 'อ.สมฤทัย' },
  },
  {
    id: 'mock-sc5',
    code: '24531264',
    name: 'พฤติกรรมสารสนเทศและผู้ใช้สารสนเทศ',
    term: '1/2569',
    group: '1',
    totalSessions: 15,
    teacherName: 'อ.สมฤทัย',
    day: 'FR',
    time: '09:00-11:50',
    room: 'QS2-415',
    teacher: { id: 't3', name: 'อ.สมฤทัย' },
  },
  {
    id: 'mock-sc6',
    code: '89539764',
    name: 'การเป็นผู้ประกอบการในศตวรรษที่ 21',
    term: '1/2569',
    group: '8',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.วรรณประภา',
    day: 'FR',
    time: '13:00-15:50',
    room: 'BBS-204',
    teacher: { id: 't6', name: 'ผศ.ดร.วรรณประภา' },
  },
];

export const MOCK_STUDENT_SUMMARIES = [
  {
    course: MOCK_STUDENT_COURSES[0],
    totalSessions: 15,
    approvedLeaves: 1,
    attended: 14,
    percentage: 93,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: MOCK_STUDENT_COURSES[1],
    totalSessions: 15,
    approvedLeaves: 1,
    attended: 14,
    percentage: 93,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: MOCK_STUDENT_COURSES[2],
    totalSessions: 15,
    approvedLeaves: 0,
    attended: 15,
    percentage: 100,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: MOCK_STUDENT_COURSES[3],
    totalSessions: 15,
    approvedLeaves: 0,
    attended: 15,
    percentage: 100,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: MOCK_STUDENT_COURSES[4],
    totalSessions: 15,
    approvedLeaves: 1,
    attended: 14,
    percentage: 93,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: MOCK_STUDENT_COURSES[5],
    totalSessions: 15,
    approvedLeaves: 0,
    attended: 15,
    percentage: 100,
    quotaLimit: 3,
    overQuota: false,
  },
];

export const MOCK_STUDENT_LEAVES = [
  {
    id: 101,
    studentId: 'student-mock',
    courseId: 'mock-sc1',
    courseCode: '24527664',
    courseName: '24527664 การวิเคราะห์และออกแบบระบบสารสนเทศ',
    courseTitle: 'การวิเคราะห์และออกแบบระบบสารสนเทศ',
    courseTerm: '1/2569',
    courseGroup: '01',
    teacherName: 'ผศ.ดร.อัครา',
    type: 'ลาป่วย',
    period: 'เต็มคาบเรียน 3 ชั่วโมง',
    startDate: '2026-08-20',
    endDate: '2026-08-20',
    reason: 'มีไข้สูงและปวดศีรษะ พบแพทย์ตามใบรับรองแพทย์',
    attachment: null,
    status: 'อนุมัติ',
    teacherComment: 'อนุมัติการลาตามระเบียบเรียบร้อย',
    createdAt: '2026-08-20T08:30:00.000Z',
  },
  {
    id: 102,
    studentId: 'student-mock',
    courseId: 'mock-sc2',
    courseCode: '24527564',
    courseName: '24527564 การประยุกต์โปรแกรมโอเพนซอร์ส',
    courseTitle: 'การประยุกต์โปรแกรมโอเพนซอร์ส',
    courseTerm: '1/2569',
    courseGroup: '01',
    teacherName: 'ดร.ธีรเดช',
    type: 'ลากิจส่วนตัว',
    period: 'เต็มคาบเรียน 3 ชั่วโมง',
    startDate: '2026-08-25',
    endDate: '2026-08-25',
    reason: 'เข้าร่วมงานบวชพี่ชายต่างจังหวัด',
    attachment: null,
    status: 'รออนุมัติ',
    teacherComment: null,
    createdAt: '2026-08-24T14:15:00.000Z',
  },
  {
    id: 103,
    studentId: 'student-mock',
    courseId: 'mock-sc4',
    courseCode: '24537364',
    courseName: '24537364 ระบบห้องสมุดอัตโนมัติ',
    courseTitle: 'ระบบห้องสมุดอัตโนมัติ',
    courseTerm: '1/2569',
    courseGroup: '01',
    teacherName: 'ผศ.ดร.ปรียานุช',
    type: 'ลากิจกรรม',
    period: 'เต็มคาบเรียน 3 ชั่วโมง',
    startDate: '2026-08-15',
    endDate: '2026-08-15',
    reason: 'เป็นตัวแทนเข้าร่วมการแข่งขันนำเสนอโครงงานวิชาการของมหาวิทยาลัย',
    attachment: null,
    status: 'อนุมัติ',
    teacherComment: 'อนุมัติเนื่องจากเป็นตัวแทนกิจกรรมคณะ/มหาวิทยาลัย',
    createdAt: '2026-08-14T10:00:00.000Z',
  },
];

export const PAST_SEMESTER_COURSES = [
  {
    id: 'hist-c1',
    code: '24521464',
    name: 'การเขียนโปรแกรมเชิงวัตถุ (Object-Oriented Programming)',
    term: '2/2568',
    group: '01',
    totalSessions: 15,
    teacherName: 'ดร.ธีรเดช',
    day: 'WE',
    time: '09:00-11:50',
    room: 'IF-4C01',
  },
  {
    id: 'hist-c2',
    code: '24522364',
    name: 'โครงสร้างข้อมูลและขั้นตอนวิธี (Data Structures & Algorithms)',
    term: '2/2568',
    group: '01',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.อัครา',
    day: 'TH',
    time: '13:00-15:50',
    room: 'IF-3M210',
  },
  {
    id: 'hist-c3',
    code: '24523164',
    name: 'ระบบฐานข้อมูล (Database Systems)',
    term: '2/2568',
    group: '01',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.ศรีหทัย',
    day: 'TU',
    time: '09:00-11:50',
    room: 'IF-3M280',
  },
  {
    id: 'hist-c4',
    code: '24510164',
    name: 'เทคโนโลยีสารสนเทศเบื้องต้น (Introduction to IT)',
    term: '1/2568',
    group: '01',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.ขวัญชฎิล',
    day: 'MO',
    time: '09:00-11:50',
    room: 'IF-3M280',
  },
  {
    id: 'hist-c5',
    code: '24510264',
    name: 'การโปรแกรมคอมพิวเตอร์พื้นฐาน (Fundamentals of Computer Programming)',
    term: '1/2568',
    group: '01',
    totalSessions: 15,
    teacherName: 'ผศ.ดร.ฉัชพน',
    day: 'TH',
    time: '13:00-15:50',
    room: 'IF-4C01',
  },
];

export const PAST_SEMESTER_SUMMARIES = [
  {
    course: PAST_SEMESTER_COURSES[0],
    totalSessions: 15,
    approvedLeaves: 1,
    attended: 14,
    percentage: 93,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: PAST_SEMESTER_COURSES[1],
    totalSessions: 15,
    approvedLeaves: 0,
    attended: 15,
    percentage: 100,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: PAST_SEMESTER_COURSES[2],
    totalSessions: 15,
    approvedLeaves: 2,
    attended: 13,
    percentage: 86,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: PAST_SEMESTER_COURSES[3],
    totalSessions: 15,
    approvedLeaves: 0,
    attended: 15,
    percentage: 100,
    quotaLimit: 3,
    overQuota: false,
  },
  {
    course: PAST_SEMESTER_COURSES[4],
    totalSessions: 15,
    approvedLeaves: 1,
    attended: 14,
    percentage: 93,
    quotaLimit: 3,
    overQuota: false,
  },
];

export const PAST_SEMESTER_LEAVES = [
  {
    id: 201,
    studentId: 'student-mock',
    courseId: 'hist-c1',
    courseCode: '24521464',
    courseName: '24521464 การเขียนโปรแกรมเชิงวัตถุ',
    courseTitle: 'การเขียนโปรแกรมเชิงวัตถุ',
    courseTerm: '2/2568',
    courseGroup: '01',
    teacherName: 'ดร.ธีรเดช',
    type: 'ลาป่วย',
    period: 'เต็มคาบเรียน 3 ชั่วโมง',
    startDate: '2025-11-12',
    endDate: '2025-11-12',
    reason: 'ติดเชื้อทางเดินหายใจ มีอาการไข้และไอหนัก พบแพทย์',
    attachment: null,
    status: 'อนุมัติ',
    teacherComment: 'อนุมัติการลาตามใบรับรองแพทย์',
    createdAt: '2025-11-12T08:00:00.000Z',
  },
  {
    id: 202,
    studentId: 'student-mock',
    courseId: 'hist-c3',
    courseCode: '24523164',
    courseName: '24523164 ระบบฐานข้อมูล',
    courseTitle: 'ระบบฐานข้อมูล',
    courseTerm: '2/2568',
    courseGroup: '01',
    teacherName: 'ผศ.ดร.ศรีหทัย',
    type: 'ลากิจส่วนตัว',
    period: 'เต็มคาบเรียน 3 ชั่วโมง',
    startDate: '2025-12-05',
    endDate: '2025-12-05',
    reason: 'มีธุระสำคัญกับครอบครัวที่ต่างจังหวัด',
    attachment: null,
    status: 'อนุมัติ',
    teacherComment: 'อนุมัติ ให้ติดตามงานกับเพื่อนในชั้นเรียน',
    createdAt: '2025-12-04T13:20:00.000Z',
  },
  {
    id: 203,
    studentId: 'student-mock',
    courseId: 'hist-c3',
    courseCode: '24523164',
    courseName: '24523164 ระบบฐานข้อมูล',
    courseTitle: 'ระบบฐานข้อมูล',
    courseTerm: '2/2568',
    courseGroup: '01',
    teacherName: 'ผศ.ดร.ศรีหทัย',
    type: 'ลากิจกรรม',
    period: 'เต็มคาบเรียน 3 ชั่วโมง',
    startDate: '2026-01-18',
    endDate: '2026-01-18',
    reason: 'เข้าร่วมค่ายบำเพ็ญประโยชน์ของสโมสรนิสิต',
    attachment: null,
    status: 'อนุมัติ',
    teacherComment: 'อนุมัติ มีหนังสือขอตัวจากสโมสรนิสิต',
    createdAt: '2026-01-15T09:00:00.000Z',
  },
  {
    id: 301,
    studentId: 'student-mock',
    courseId: 'hist-c5',
    courseCode: '24510264',
    courseName: '24510264 การโปรแกรมคอมพิวเตอร์พื้นฐาน',
    courseTitle: 'การโปรแกรมคอมพิวเตอร์พื้นฐาน',
    courseTerm: '1/2568',
    courseGroup: '01',
    teacherName: 'ผศ.ดร.ฉัชพน',
    type: 'ลาป่วย',
    period: 'เต็มคาบเรียน 3 ชั่วโมง',
    startDate: '2025-08-10',
    endDate: '2025-08-10',
    reason: 'อาหารเป็นพิษ มีไข้และอ่อนเพลีย',
    attachment: null,
    status: 'อนุมัติ',
    teacherComment: 'อนุมัติ พักผ่อนให้หายดี',
    createdAt: '2025-08-10T07:45:00.000Z',
  },
];

export async function getStudentData(studentId) {
  try {
    const realCourses = await listCoursesForStudent(studentId);
    if (realCourses && realCourses.length > 0) {
      const rawSummaries = await Promise.all(realCourses.map((c) => getAttendanceSummary(studentId, c.id)));
      const summaries = rawSummaries.filter(Boolean);
      const rawLeaves = await listLeavesForStudent(studentId);
      const leaves = await Promise.all(
        rawLeaves.map(async (l) => {
          const course = await getCourse(l.courseId);
          return {
            ...l,
            courseCode: course?.code || '',
            courseName: course ? `${course.code} ${course.name}` : '-',
            courseTitle: course?.name || '',
            courseTerm: course?.term || '',
            courseGroup: course?.group || '',
            teacherName: course?.teacher?.name || course?.teacherName || '',
          };
        })
      );
      return {
        courses: realCourses,
        summaries: [...summaries, ...PAST_SEMESTER_SUMMARIES],
        leaves: [...leaves, ...PAST_SEMESTER_LEAVES],
        usingMock: false,
      };
    }
  } catch (err) {
    console.error('Error fetching real student data, falling back to mock:', err);
  }

  // Fallback to mock data for demo / prototype
  return {
    courses: [...MOCK_STUDENT_COURSES, ...PAST_SEMESTER_COURSES],
    summaries: [...MOCK_STUDENT_SUMMARIES, ...PAST_SEMESTER_SUMMARIES],
    leaves: [...MOCK_STUDENT_LEAVES, ...PAST_SEMESTER_LEAVES],
    usingMock: true,
  };
}
